### ISSUE TITLE
General Usage Instructions

### ISSUE THREAD

**Issue by Aleksa-ri** [addestromberg/OpenhabInUnity#1]
Hello,

I am using Unity 2019.2, but  i do not have any Visual Studio installed.

I want to use your OpenHABinUnity github repo. I want to ask you, how should i install EvtSource and InfluxDB.Client. Do i have to install Visual Studio first? 

I need this for an Seminar Work for my university Project.

Thanks you,

Aleksa

**Comment by addestromberg** [comment]
Hi.

I do not think you need visual studio for the libraries. Just download the
files from respective repo and add within projectfolder in unity. Unity
should take care of the rest.

/Adde

Den fre 22 maj 2020 13:19Aleksa-ri <notifications@github.com> skrev:

**Comment by addestromberg** [comment]
Just wanted to check in and see if you managed to get it working. If you downloaded or cloned the repo all libraries except Json.Net for Unity should be included. Json.Net for Unity is available from assetstore, I realized that the url to asset have been changed so[ try this url](https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347) instead.

**Comment by Aleksa-ri** [comment]
I want to ask, is it a 3D or a 2D Project, that you have to create in Unity?

**Comment by addestromberg** [comment]
It's created in a 3d project.

**Comment by Aleksa-ri** [comment]
ok thank you i will try to install all again, and then i will write you if i have any Problems, thanks !

**Comment by addestromberg** [comment]
I tried to import on 2019.2.21 and for some reason the Prefabs didn't work. So try creating "new" widgets by:

- First import Json.Net for Unity (Doesn't matter were it is located as long as it is in project asset folder.)

- Clone the repo into a newly created Unity project with "git clone https://github.com/addestromberg/OpenhabInUnity.git" and make sure the new files are imported within unity afterwards.

- Create a new Scene and add a tag called "Eventbus". Create a gameobject and assign it to Eventbus tag, then add "EventController" component to it. All scripts are located in "_Scripts/Openhab" folder with the "controllers" in subfolder "Controllers". Check the server URI setting so that is correct in EventController component. You now have the ability to listen to eventstreams from openhab.

- For simpliest test. Add a text object in a canvas. And add a "DummyWidget" component to this object. (Available "widget" scripts is located under "_Scripts/Openhab/Views"). Check for some test Item in openhab and copy paste the Item name to Item property in the component.

- Run the scene and see if you get Itemvalue from openhab. 

If there is no errors but you still don't get any values from Openhab. Try openhab test api from "REST Documentation" in openhab available from PaperUI. This is something you probably want anyway as you build on.
